# Generated by Django 3.2 on 2022-09-23 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_todo_todo_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='todo.todo'),
        ),
    ]
